#!/bin/bash
# DEPLOYMENT FINAL A RAILWAY - Ejecuta Esto Paso a Paso

echo "════════════════════════════════════════════════════════════════"
echo "  🚀 DEPLOYMENT A RAILWAY - YOUTUBE TRANSCRIBER PRO"
echo "════════════════════════════════════════════════════════════════"
echo ""

# Paso 1: Verificar código está pusheado
echo "📦 PASO 1: Verificando código..."
git status
echo ""
read -p "¿El código está limpio? (y/n): " clean
if [ "$clean" != "y" ]; then
    echo "❌ Pushea los cambios primero"
    exit 1
fi

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  ⚙️  PASO 2: CONFIGURAR RAILWAY"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Ve a: https://railway.app/dashboard"
echo ""
echo "1. Si NO tienes proyecto:"
echo "   - Click 'New Project'"
echo "   - Selecciona 'Deploy from GitHub repo'"
echo "   - Busca: inginddie/youtube-transcriber"
echo "   - Click 'Deploy Now'"
echo ""
echo "2. Si YA tienes proyecto:"
echo "   - Abre tu proyecto existente"
echo "   - Click en tu servicio"
echo ""
read -p "Presiona Enter cuando hayas abierto el proyecto en Railway..."

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🌿 PASO 3: CONFIGURAR BRANCH"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "En Railway:"
echo "1. Click en tu servicio"
echo "2. Ve a: Settings → Source"
echo "3. Branch: Selecciona 'claude/code-review-analysis-pUkeS'"
echo "4. Click 'Save'"
echo ""
read -p "Presiona Enter cuando hayas configurado el branch..."

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🔐 PASO 4: VARIABLES DE ENTORNO"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "En Railway, ve a: Variables tab"
echo ""
echo "Agrega estas 6 VARIABLES (Click '+ New Variable' 6 veces):"
echo ""
echo "─────────────────────────────────────────────────────────────────"
echo "Variable 1:"
echo "  Name:  OPENAI_API_KEY"
echo "  Value: [TU API KEY REAL DE OPENAI]"
echo ""
echo "Variable 2:"
echo "  Name:  REQUIRE_AUTH"
echo "  Value: true"
echo ""
echo "Variable 3:"
echo "  Name:  ACCESS_CODE"
echo "  Value: 83dtfmoj7Grq4UBmtI4vcJYoABo5CTs5H68FNVOvszE"
echo ""
echo "Variable 4:"
echo "  Name:  MAX_TRANSCRIPTIONS_PER_HOUR"
echo "  Value: 3"
echo ""
echo "Variable 5:"
echo "  Name:  MAX_SEARCHES_PER_MINUTE"
echo "  Value: 10"
echo ""
echo "Variable 6:"
echo "  Name:  MAX_CHATS_PER_MINUTE"
echo "  Value: 5"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "⚠️  IMPORTANTE:"
echo "   - Reemplaza [TU API KEY REAL DE OPENAI] con tu key real"
echo "   - Copia el ACCESS_CODE exactamente como está arriba"
echo "   - Los números deben ser sin comillas"
echo ""
read -p "Presiona Enter cuando hayas agregado las 6 variables..."

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🏗️  PASO 5: MONITOREAR BUILD"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Railway comenzará a desplegar automáticamente."
echo ""
echo "1. Ve a: Deployments tab"
echo "2. Click en el deployment activo"
echo "3. Ve a 'Build Logs' para ver el progreso"
echo ""
echo "Deberías ver:"
echo "  Step 1/8: FROM python:3.11-slim"
echo "  Step 2/8: RUN apt-get update..."
echo "  ..."
echo "  Step 8/8: CMD [\"python\", \"app_gradio.py\"]"
echo "  Successfully built"
echo ""
echo "Luego en 'Deploy Logs':"
echo "  🔧 Setting up directories..."
echo "  ✅ Security manager imported successfully"
echo "  🚀 Launching Gradio interface..."
echo "  Running on local URL: http://0.0.0.0:7860"
echo ""
read -p "Presiona Enter cuando el deployment diga 'Success'..."

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🌐 PASO 6: OBTENER URL"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1. En Railway, ve a: Settings → Domains"
echo "2. Click 'Generate Domain'"
echo "3. Railway generará una URL como:"
echo "   https://youtube-transcriber-production-XXXX.up.railway.app"
echo ""
read -p "Presiona Enter cuando tengas la URL..."

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🧪 PASO 7: PROBAR LA APLICACIÓN"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Ahora vamos a probar que todo funciona:"
echo ""
echo "TEST 1: Abrir la app"
echo "  → Abre la URL de Railway en tu navegador"
echo "  → Deberías ver: 🎥 YouTube Transcriber Pro"
echo "  → SIN banner rojo (porque REQUIRE_AUTH=true)"
echo ""
read -p "¿Ves la aplicación? (y/n): " see_app
echo ""

echo "TEST 2: Verificar autenticación"
echo "  → Ve a la pestaña '🔐 Login'"
echo "  → Deberías ver un campo para Access Code"
echo ""
read -p "¿Ves la pestaña de Login? (y/n): " see_login
echo ""

echo "TEST 3: Hacer login"
echo "  → En 'Access Code', ingresa:"
echo "    83dtfmoj7Grq4UBmtI4vcJYoABo5CTs5H68FNVOvszE"
echo "  → Click '🔓 Login'"
echo "  → Deberías ver:"
echo "    ✅ Login Successful!"
echo "    Session ID: ..."
echo ""
read -p "¿Login exitoso? (y/n): " login_ok
echo ""

echo "TEST 4: Verificar seguridad activa"
echo "  → Mira la barra superior"
echo "  → Deberías ver:"
echo "    🟢 Status: Authenticated & Protected ✅"
echo "    Protection: 🛡️ ACTIVE"
echo ""
read -p "¿Ves protección activa? (y/n): " protection_ok
echo ""

echo "TEST 5: Probar transcripción (opcional)"
echo "  → Ve a '📝 Transcribe Videos'"
echo "  → Ingresa una URL corta de YouTube"
echo "  → Click '🚀 Transcribe Videos'"
echo "  → Debería empezar a procesar"
echo ""
read -p "¿Quieres probar una transcripción? (y/n): " test_transcribe

echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  ✅ DEPLOYMENT COMPLETADO"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Tu aplicación está desplegada y PROTEGIDA ✅"
echo ""
echo "📋 INFORMACIÓN PARA COMPARTIR:"
echo ""
echo "  URL: [La URL de Railway que generaste]"
echo "  Access Code: 83dtfmoj7Grq4UBmtI4vcJYoABo5CTs5H68FNVOvszE"
echo ""
echo "  Instrucciones para usuarios:"
echo "  1. Abrir URL"
echo "  2. Ir a pestaña '🔐 Login'"
echo "  3. Ingresar Access Code"
echo "  4. Click Login"
echo "  5. ¡Listo para transcribir!"
echo ""
echo "🔒 SEGURIDAD ACTIVA:"
echo "  ✅ Login requerido"
echo "  ✅ Rate limiting activo"
echo "  ✅ Session timeout: 1 hora"
echo "  ✅ Límites:"
echo "     - 3 transcripciones/hora"
echo "     - 10 búsquedas/minuto"
echo "     - 5 mensajes chat/minuto"
echo ""
echo "📊 MONITOREO:"
echo "  - Railway Dashboard → Deployments (ver logs)"
echo "  - Railway Dashboard → Metrics (CPU, memoria)"
echo "  - En la app → Tab '🔒 Security' (ver estado)"
echo ""
echo "🎉 ¡FELICIDADES! Deployment exitoso."
echo ""
echo "════════════════════════════════════════════════════════════════"
