[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python -c 'from config import create_directories; create_directories()'"]

[start]
cmd = "python app_gradio_secure.py"
