#!/bin/bash
# Railway Environment Variables Setup Script
# Copy these values to Railway Dashboard → Variables

echo "=================================================="
echo "RAILWAY DEPLOYMENT - ENVIRONMENT VARIABLES"
echo "=================================================="
echo ""
echo "🔑 Copy and paste these in Railway Dashboard:"
echo ""
echo "---------------------------------------------------"
echo "# 1. OpenAI API Key (REQUIRED)"
echo "---------------------------------------------------"
echo "OPENAI_API_KEY=sk-proj-YOUR_ACTUAL_API_KEY_HERE"
echo ""
echo "---------------------------------------------------"
echo "# 2. Security Settings (Authentication)"
echo "---------------------------------------------------"
echo "REQUIRE_AUTH=true"
echo "ACCESS_CODE=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || echo "GENERATE_YOUR_OWN_CODE")"
echo ""
echo "---------------------------------------------------"
echo "# 3. Rate Limiting (Production Conservative)"
echo "---------------------------------------------------"
echo "MAX_TRANSCRIPTIONS_PER_HOUR=3"
echo "MAX_SEARCHES_PER_MINUTE=10"
echo "MAX_CHATS_PER_MINUTE=5"
echo ""
echo "=================================================="
echo ""
echo "📋 INSTRUCTIONS:"
echo ""
echo "1. Go to: https://railway.app/dashboard"
echo "2. Select your project: youtube-transcriber"
echo "3. Click on your service"
echo "4. Go to: Variables tab"
echo "5. Click: + New Variable"
echo "6. Add each variable above (6 variables total)"
echo "7. Railway will automatically redeploy"
echo ""
echo "⚠️  IMPORTANT:"
echo "- Replace sk-proj-YOUR_ACTUAL_API_KEY_HERE with your real OpenAI API key"
echo "- Keep the ACCESS_CODE generated above (or generate your own)"
echo "- Save this ACCESS_CODE securely - you'll need it to login!"
echo ""
echo "=================================================="
